/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn1c/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -D /home/sid/mme/binds/src/s1ap/c -fcompound-names -no-gen-example`
 */

#include "AreaScopeOfQMC.h"

static asn_oer_constraints_t asn_OER_type_AreaScopeOfQMC_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_AreaScopeOfQMC_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  3 }	/* (0..3,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_AreaScopeOfQMC_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AreaScopeOfQMC, choice.cellBased),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CellBasedQMC,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cellBased"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AreaScopeOfQMC, choice.tABased),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TABasedQMC,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tABased"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AreaScopeOfQMC, choice.tAIBased),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TAIBasedQMC,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tAIBased"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AreaScopeOfQMC, choice.pLMNAreaBased),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PLMNAreaBasedQMC,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pLMNAreaBased"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_AreaScopeOfQMC_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cellBased */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* tABased */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* tAIBased */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* pLMNAreaBased */
};
asn_CHOICE_specifics_t asn_SPC_AreaScopeOfQMC_specs_1 = {
	sizeof(struct AreaScopeOfQMC),
	offsetof(struct AreaScopeOfQMC, _asn_ctx),
	offsetof(struct AreaScopeOfQMC, present),
	sizeof(((struct AreaScopeOfQMC *)0)->present),
	asn_MAP_AreaScopeOfQMC_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0,
	4	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_AreaScopeOfQMC = {
	"AreaScopeOfQMC",
	"AreaScopeOfQMC",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_AreaScopeOfQMC_constr_1, &asn_PER_type_AreaScopeOfQMC_constr_1, CHOICE_constraint },
	asn_MBR_AreaScopeOfQMC_1,
	4,	/* Elements count */
	&asn_SPC_AreaScopeOfQMC_specs_1	/* Additional specs */
};

