/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn1c/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -D /home/sid/mme/binds/src/s1ap/c -fcompound-names -no-gen-example`
 */

#ifndef	_Bearers_SubjectToStatusTransfer_Item_H_
#define	_Bearers_SubjectToStatusTransfer_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "E-RAB-ID.h"
#include "COUNTvalue.h"
#include "ReceiveStatusofULPDCPSDUs.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* Bearers-SubjectToStatusTransfer-Item */
typedef struct Bearers_SubjectToStatusTransfer_Item {
	E_RAB_ID_t	 e_RAB_ID;
	COUNTvalue_t	 uL_COUNTvalue;
	COUNTvalue_t	 dL_COUNTvalue;
	ReceiveStatusofULPDCPSDUs_t	*receiveStatusofULPDCPSDUs	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Bearers_SubjectToStatusTransfer_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Bearers_SubjectToStatusTransfer_Item;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolExtensionContainer.h"

#endif	/* _Bearers_SubjectToStatusTransfer_Item_H_ */
#include <asn_internal.h>
