/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn1c/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -D /home/sid/mme/binds/src/s1ap/c -fcompound-names -no-gen-example`
 */

#include "BroadcastCancelledAreaList.h"

static asn_oer_constraints_t asn_OER_type_BroadcastCancelledAreaList_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_BroadcastCancelledAreaList_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  2 }	/* (0..2,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_BroadcastCancelledAreaList_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BroadcastCancelledAreaList, choice.cellID_Cancelled),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CellID_Cancelled,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cellID-Cancelled"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BroadcastCancelledAreaList, choice.tAI_Cancelled),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TAI_Cancelled,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tAI-Cancelled"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BroadcastCancelledAreaList, choice.emergencyAreaID_Cancelled),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EmergencyAreaID_Cancelled,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"emergencyAreaID-Cancelled"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_BroadcastCancelledAreaList_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cellID-Cancelled */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* tAI-Cancelled */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* emergencyAreaID-Cancelled */
};
static asn_CHOICE_specifics_t asn_SPC_BroadcastCancelledAreaList_specs_1 = {
	sizeof(struct BroadcastCancelledAreaList),
	offsetof(struct BroadcastCancelledAreaList, _asn_ctx),
	offsetof(struct BroadcastCancelledAreaList, present),
	sizeof(((struct BroadcastCancelledAreaList *)0)->present),
	asn_MAP_BroadcastCancelledAreaList_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	3	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_BroadcastCancelledAreaList = {
	"BroadcastCancelledAreaList",
	"BroadcastCancelledAreaList",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_BroadcastCancelledAreaList_constr_1, &asn_PER_type_BroadcastCancelledAreaList_constr_1, CHOICE_constraint },
	asn_MBR_BroadcastCancelledAreaList_1,
	3,	/* Elements count */
	&asn_SPC_BroadcastCancelledAreaList_specs_1	/* Additional specs */
};

