/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn1c/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -D /home/sid/mme/binds/src/s1ap/c -fcompound-names -no-gen-example`
 */

#ifndef	_CNTypeRestrictions_H_
#define	_CNTypeRestrictions_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CNTypeRestrictions_Item;

/* CNTypeRestrictions */
typedef struct CNTypeRestrictions {
	A_SEQUENCE_OF(struct CNTypeRestrictions_Item) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CNTypeRestrictions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CNTypeRestrictions;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CNTypeRestrictions-Item.h"

#endif	/* _CNTypeRestrictions_H_ */
#include <asn_internal.h>
