/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn1c/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -D /home/sid/mme/binds/src/s1ap/c -fcompound-names -no-gen-example`
 */

#ifndef	_CNType_H_
#define	_CNType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CNType {
	CNType_fiveGCForbidden	= 0,
	/*
	 * Enumeration is extensible
	 */
	CNType_epc_Forbiddden	= 1
} e_CNType;

/* CNType */
typedef long	 CNType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_CNType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_CNType;
extern const asn_INTEGER_specifics_t asn_SPC_CNType_specs_1;
asn_struct_free_f CNType_free;
asn_struct_print_f CNType_print;
asn_constr_check_f CNType_constraint;
ber_type_decoder_f CNType_decode_ber;
der_type_encoder_f CNType_encode_der;
xer_type_decoder_f CNType_decode_xer;
xer_type_encoder_f CNType_encode_xer;
oer_type_decoder_f CNType_decode_oer;
oer_type_encoder_f CNType_encode_oer;
per_type_decoder_f CNType_decode_uper;
per_type_encoder_f CNType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CNType_H_ */
#include <asn_internal.h>
