/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn1c/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -D /home/sid/mme/binds/src/s1ap/c -fcompound-names -no-gen-example`
 */

#ifndef	_DAPSRequestInfo_H_
#define	_DAPSRequestInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DAPSRequestInfo__dAPSIndicator {
	DAPSRequestInfo__dAPSIndicator_dAPS_HO_required	= 0
	/*
	 * Enumeration is extensible
	 */
} e_DAPSRequestInfo__dAPSIndicator;

/* Forward declarations */
struct ProtocolExtensionContainer;

/* DAPSRequestInfo */
typedef struct DAPSRequestInfo {
	long	 dAPSIndicator;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DAPSRequestInfo_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_dAPSIndicator_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_DAPSRequestInfo;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolExtensionContainer.h"

#endif	/* _DAPSRequestInfo_H_ */
#include <asn_internal.h>
