/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn1c/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -D /home/sid/mme/binds/src/s1ap/c -fcompound-names -no-gen-example`
 */

#ifndef	_DAPSResponseInfo_H_
#define	_DAPSResponseInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DAPSResponseInfo__dapsresponseindicator {
	DAPSResponseInfo__dapsresponseindicator_dAPS_HO_accepted	= 0,
	DAPSResponseInfo__dapsresponseindicator_dAPS_HO_not_accepted	= 1
	/*
	 * Enumeration is extensible
	 */
} e_DAPSResponseInfo__dapsresponseindicator;

/* Forward declarations */
struct ProtocolExtensionContainer;

/* DAPSResponseInfo */
typedef struct DAPSResponseInfo {
	long	 dapsresponseindicator;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DAPSResponseInfo_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_dapsresponseindicator_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_DAPSResponseInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_DAPSResponseInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_DAPSResponseInfo_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolExtensionContainer.h"

#endif	/* _DAPSResponseInfo_H_ */
#include <asn_internal.h>
