/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn1c/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -D /home/sid/mme/binds/src/s1ap/c -fcompound-names -no-gen-example`
 */

#include "DLCOUNT-PDCP-SNlength.h"

static asn_oer_constraints_t asn_OER_type_DLCOUNT_PDCP_SNlength_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_DLCOUNT_PDCP_SNlength_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  2 }	/* (0..2,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_DLCOUNT_PDCP_SNlength_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DLCOUNT_PDCP_SNlength, choice.dLCOUNTValuePDCP_SNlength12),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_COUNTvalue,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dLCOUNTValuePDCP-SNlength12"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DLCOUNT_PDCP_SNlength, choice.dLCOUNTValuePDCP_SNlength15),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_COUNTValueExtended,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dLCOUNTValuePDCP-SNlength15"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DLCOUNT_PDCP_SNlength, choice.dLCOUNTValuePDCP_SNlength18),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_COUNTvaluePDCP_SNlength18,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dLCOUNTValuePDCP-SNlength18"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_DLCOUNT_PDCP_SNlength_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dLCOUNTValuePDCP-SNlength12 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* dLCOUNTValuePDCP-SNlength15 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* dLCOUNTValuePDCP-SNlength18 */
};
asn_CHOICE_specifics_t asn_SPC_DLCOUNT_PDCP_SNlength_specs_1 = {
	sizeof(struct DLCOUNT_PDCP_SNlength),
	offsetof(struct DLCOUNT_PDCP_SNlength, _asn_ctx),
	offsetof(struct DLCOUNT_PDCP_SNlength, present),
	sizeof(((struct DLCOUNT_PDCP_SNlength *)0)->present),
	asn_MAP_DLCOUNT_PDCP_SNlength_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	3	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_DLCOUNT_PDCP_SNlength = {
	"DLCOUNT-PDCP-SNlength",
	"DLCOUNT-PDCP-SNlength",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_DLCOUNT_PDCP_SNlength_constr_1, &asn_PER_type_DLCOUNT_PDCP_SNlength_constr_1, CHOICE_constraint },
	asn_MBR_DLCOUNT_PDCP_SNlength_1,
	3,	/* Elements count */
	&asn_SPC_DLCOUNT_PDCP_SNlength_specs_1	/* Additional specs */
};

