/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-PDU-Contents"
 * 	found in "asn1c/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -D /home/sid/mme/binds/src/s1ap/c -fcompound-names -no-gen-example`
 */

#include "E-RABToBeUpdatedItem.h"

static asn_TYPE_member_t asn_MBR_E_RABToBeUpdatedItem_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E_RABToBeUpdatedItem, e_RAB_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E_RAB_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"e-RAB-ID"
		},
	{ ATF_POINTER, 2, offsetof(struct E_RABToBeUpdatedItem, securityIndication),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SecurityIndication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"securityIndication"
		},
	{ ATF_POINTER, 1, offsetof(struct E_RABToBeUpdatedItem, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_8194P0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_E_RABToBeUpdatedItem_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_E_RABToBeUpdatedItem_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_E_RABToBeUpdatedItem_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* e-RAB-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* securityIndication */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-Extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_E_RABToBeUpdatedItem_specs_1 = {
	sizeof(struct E_RABToBeUpdatedItem),
	offsetof(struct E_RABToBeUpdatedItem, _asn_ctx),
	asn_MAP_E_RABToBeUpdatedItem_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_E_RABToBeUpdatedItem_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_E_RABToBeUpdatedItem = {
	"E-RABToBeUpdatedItem",
	"E-RABToBeUpdatedItem",
	&asn_OP_SEQUENCE,
	asn_DEF_E_RABToBeUpdatedItem_tags_1,
	sizeof(asn_DEF_E_RABToBeUpdatedItem_tags_1)
		/sizeof(asn_DEF_E_RABToBeUpdatedItem_tags_1[0]), /* 1 */
	asn_DEF_E_RABToBeUpdatedItem_tags_1,	/* Same as above */
	sizeof(asn_DEF_E_RABToBeUpdatedItem_tags_1)
		/sizeof(asn_DEF_E_RABToBeUpdatedItem_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_E_RABToBeUpdatedItem_1,
	3,	/* Elements count */
	&asn_SPC_E_RABToBeUpdatedItem_specs_1	/* Additional specs */
};

