/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-PDU-Contents"
 * 	found in "asn1c/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -D /home/sid/mme/binds/src/s1ap/c -fcompound-names -no-gen-example`
 */

#ifndef	_E_RAB_IE_ContainerList_H_
#define	_E_RAB_IE_ContainerList_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProtocolIE-ContainerList.h"

#ifdef __cplusplus
extern "C" {
#endif

/* E-RAB-IE-ContainerList */
typedef ProtocolIE_ContainerList_8180P0_t	 E_RAB_IE_ContainerList_1280P0_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_E_RAB_IE_ContainerList_1280P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_E_RAB_IE_ContainerList_1280P0;
asn_struct_free_f E_RAB_IE_ContainerList_1280P0_free;
asn_struct_print_f E_RAB_IE_ContainerList_1280P0_print;
asn_constr_check_f E_RAB_IE_ContainerList_1280P0_constraint;
ber_type_decoder_f E_RAB_IE_ContainerList_1280P0_decode_ber;
der_type_encoder_f E_RAB_IE_ContainerList_1280P0_encode_der;
xer_type_decoder_f E_RAB_IE_ContainerList_1280P0_decode_xer;
xer_type_encoder_f E_RAB_IE_ContainerList_1280P0_encode_xer;
oer_type_decoder_f E_RAB_IE_ContainerList_1280P0_decode_oer;
oer_type_encoder_f E_RAB_IE_ContainerList_1280P0_encode_oer;
per_type_decoder_f E_RAB_IE_ContainerList_1280P0_decode_uper;
per_type_encoder_f E_RAB_IE_ContainerList_1280P0_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _E_RAB_IE_ContainerList_H_ */
#include <asn_internal.h>
