/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn1c/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -D /home/sid/mme/binds/src/s1ap/c -fcompound-names -no-gen-example`
 */

#include "ENB-EarlyStatusTransfer-TransparentContainer.h"

static asn_TYPE_member_t asn_MBR_ENB_EarlyStatusTransfer_TransparentContainer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ENB_EarlyStatusTransfer_TransparentContainer, bearers_SubjectToEarlyStatusTransferList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Bearers_SubjectToEarlyStatusTransferList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"bearers-SubjectToEarlyStatusTransferList"
		},
	{ ATF_POINTER, 1, offsetof(struct ENB_EarlyStatusTransfer_TransparentContainer, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_8194P0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_ENB_EarlyStatusTransfer_TransparentContainer_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_ENB_EarlyStatusTransfer_TransparentContainer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ENB_EarlyStatusTransfer_TransparentContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* bearers-SubjectToEarlyStatusTransferList */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* iE-Extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_ENB_EarlyStatusTransfer_TransparentContainer_specs_1 = {
	sizeof(struct ENB_EarlyStatusTransfer_TransparentContainer),
	offsetof(struct ENB_EarlyStatusTransfer_TransparentContainer, _asn_ctx),
	asn_MAP_ENB_EarlyStatusTransfer_TransparentContainer_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_ENB_EarlyStatusTransfer_TransparentContainer_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ENB_EarlyStatusTransfer_TransparentContainer = {
	"ENB-EarlyStatusTransfer-TransparentContainer",
	"ENB-EarlyStatusTransfer-TransparentContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ENB_EarlyStatusTransfer_TransparentContainer_tags_1,
	sizeof(asn_DEF_ENB_EarlyStatusTransfer_TransparentContainer_tags_1)
		/sizeof(asn_DEF_ENB_EarlyStatusTransfer_TransparentContainer_tags_1[0]), /* 1 */
	asn_DEF_ENB_EarlyStatusTransfer_TransparentContainer_tags_1,	/* Same as above */
	sizeof(asn_DEF_ENB_EarlyStatusTransfer_TransparentContainer_tags_1)
		/sizeof(asn_DEF_ENB_EarlyStatusTransfer_TransparentContainer_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ENB_EarlyStatusTransfer_TransparentContainer_1,
	2,	/* Elements count */
	&asn_SPC_ENB_EarlyStatusTransfer_TransparentContainer_specs_1	/* Additional specs */
};

