/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn1c/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -D /home/sid/mme/binds/src/s1ap/c -fcompound-names -no-gen-example`
 */

#ifndef	_IAB_Authorized_H_
#define	_IAB_Authorized_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IAB_Authorized {
	IAB_Authorized_authorized	= 0,
	IAB_Authorized_not_authorized	= 1
	/*
	 * Enumeration is extensible
	 */
} e_IAB_Authorized;

/* IAB-Authorized */
typedef long	 IAB_Authorized_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IAB_Authorized;
asn_struct_free_f IAB_Authorized_free;
asn_struct_print_f IAB_Authorized_print;
asn_constr_check_f IAB_Authorized_constraint;
ber_type_decoder_f IAB_Authorized_decode_ber;
der_type_encoder_f IAB_Authorized_encode_der;
xer_type_decoder_f IAB_Authorized_decode_xer;
xer_type_encoder_f IAB_Authorized_encode_xer;
oer_type_decoder_f IAB_Authorized_decode_oer;
oer_type_encoder_f IAB_Authorized_encode_oer;
per_type_decoder_f IAB_Authorized_decode_uper;
per_type_encoder_f IAB_Authorized_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _IAB_Authorized_H_ */
#include <asn_internal.h>
