/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn1c/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -D /home/sid/mme/binds/src/s1ap/c -fcompound-names -no-gen-example`
 */

#ifndef	_InterSystemMeasurementItem_H_
#define	_InterSystemMeasurementItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum InterSystemMeasurementItem__subcarrierSpacingSSB {
	InterSystemMeasurementItem__subcarrierSpacingSSB_kHz15	= 0,
	InterSystemMeasurementItem__subcarrierSpacingSSB_kHz30	= 1,
	InterSystemMeasurementItem__subcarrierSpacingSSB_kHz60	= 2,
	InterSystemMeasurementItem__subcarrierSpacingSSB_kHz120	= 3,
	InterSystemMeasurementItem__subcarrierSpacingSSB_kHz240	= 4
	/*
	 * Enumeration is extensible
	 */
} e_InterSystemMeasurementItem__subcarrierSpacingSSB;

/* Forward declarations */
struct ProtocolExtensionContainer;

/* InterSystemMeasurementItem */
typedef struct InterSystemMeasurementItem {
	long	 freqBandIndicatorNR;
	long	 sSBfrequencies;
	long	 subcarrierSpacingSSB;
	long	*maxRSIndexCellQual	/* OPTIONAL */;
	OCTET_STRING_t	*sMTC	/* OPTIONAL */;
	OCTET_STRING_t	*threshRS_Index_r15	/* OPTIONAL */;
	OCTET_STRING_t	*sSBToMeasure	/* OPTIONAL */;
	OCTET_STRING_t	*sSRSSIMeasurement	/* OPTIONAL */;
	OCTET_STRING_t	*quantityConfigNR_R15	/* OPTIONAL */;
	OCTET_STRING_t	*excludedCellsToAddModList	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InterSystemMeasurementItem_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_subcarrierSpacingSSB_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_InterSystemMeasurementItem;
extern asn_SEQUENCE_specifics_t asn_SPC_InterSystemMeasurementItem_specs_1;
extern asn_TYPE_member_t asn_MBR_InterSystemMeasurementItem_1[11];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolExtensionContainer.h"

#endif	/* _InterSystemMeasurementItem_H_ */
#include <asn_internal.h>
