/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn1c/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -D /home/sid/mme/binds/src/s1ap/c -fcompound-names -no-gen-example`
 */

#include "LastVisitedPSCellInformation.h"

static int
memb_timeStay_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 40950)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_timeStay_constr_3 CC_NOTUSED = {
	{ 2, 1 }	/* (0..40950) */,
	-1};
static asn_per_constraints_t asn_PER_memb_timeStay_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  40950 }	/* (0..40950) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_LastVisitedPSCellInformation_1[] = {
	{ ATF_POINTER, 1, offsetof(struct LastVisitedPSCellInformation, pSCellID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PSCellInformation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pSCellID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LastVisitedPSCellInformation, timeStay),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_timeStay_constr_3, &asn_PER_memb_timeStay_constr_3,  memb_timeStay_constraint_1 },
		0, 0, /* No default value */
		"timeStay"
		},
	{ ATF_POINTER, 1, offsetof(struct LastVisitedPSCellInformation, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_8194P0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_LastVisitedPSCellInformation_oms_1[] = { 0, 2 };
static const ber_tlv_tag_t asn_DEF_LastVisitedPSCellInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LastVisitedPSCellInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pSCellID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* timeStay */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_LastVisitedPSCellInformation_specs_1 = {
	sizeof(struct LastVisitedPSCellInformation),
	offsetof(struct LastVisitedPSCellInformation, _asn_ctx),
	asn_MAP_LastVisitedPSCellInformation_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_LastVisitedPSCellInformation_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LastVisitedPSCellInformation = {
	"LastVisitedPSCellInformation",
	"LastVisitedPSCellInformation",
	&asn_OP_SEQUENCE,
	asn_DEF_LastVisitedPSCellInformation_tags_1,
	sizeof(asn_DEF_LastVisitedPSCellInformation_tags_1)
		/sizeof(asn_DEF_LastVisitedPSCellInformation_tags_1[0]), /* 1 */
	asn_DEF_LastVisitedPSCellInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_LastVisitedPSCellInformation_tags_1)
		/sizeof(asn_DEF_LastVisitedPSCellInformation_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_LastVisitedPSCellInformation_1,
	3,	/* Elements count */
	&asn_SPC_LastVisitedPSCellInformation_specs_1	/* Additional specs */
};

