/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn1c/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -D /home/sid/mme/binds/src/s1ap/c -fcompound-names -no-gen-example`
 */

#ifndef	_LoggedMDTTrigger_H_
#define	_LoggedMDTTrigger_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include "EventTrigger.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LoggedMDTTrigger_PR {
	LoggedMDTTrigger_PR_NOTHING,	/* No components present */
	LoggedMDTTrigger_PR_periodical,
	LoggedMDTTrigger_PR_eventTrigger
	/* Extensions may appear below */
	
} LoggedMDTTrigger_PR;

/* LoggedMDTTrigger */
typedef struct LoggedMDTTrigger {
	LoggedMDTTrigger_PR present;
	union LoggedMDTTrigger_u {
		NULL_t	 periodical;
		EventTrigger_t	 eventTrigger;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LoggedMDTTrigger_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LoggedMDTTrigger;

#ifdef __cplusplus
}
#endif

#endif	/* _LoggedMDTTrigger_H_ */
#include <asn_internal.h>
