/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn1c/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -D /home/sid/mme/binds/src/s1ap/c -fcompound-names -no-gen-example`
 */

#ifndef	_LTE_NTN_TAI_Information_H_
#define	_LTE_NTN_TAI_Information_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PLMNidentity.h"
#include "TACList-In-LTE-NTN.h"
#include "TAC.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* LTE-NTN-TAI-Information */
typedef struct LTE_NTN_TAI_Information {
	PLMNidentity_t	 servingPLMN;
	TACList_In_LTE_NTN_t	 tACList_In_LTE_NTN;
	TAC_t	*uE_Location_Derived_TAC	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LTE_NTN_TAI_Information_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LTE_NTN_TAI_Information;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolExtensionContainer.h"

#endif	/* _LTE_NTN_TAI_Information_H_ */
#include <asn_internal.h>
