/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn1c/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -D /home/sid/mme/binds/src/s1ap/c -fcompound-names -no-gen-example`
 */

#ifndef	_M_TMSI_H_
#define	_M_TMSI_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* M-TMSI */
typedef OCTET_STRING_t	 M_TMSI_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_M_TMSI_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_M_TMSI;
asn_struct_free_f M_TMSI_free;
asn_struct_print_f M_TMSI_print;
asn_constr_check_f M_TMSI_constraint;
ber_type_decoder_f M_TMSI_decode_ber;
der_type_encoder_f M_TMSI_encode_der;
xer_type_decoder_f M_TMSI_decode_xer;
xer_type_encoder_f M_TMSI_encode_xer;
oer_type_decoder_f M_TMSI_decode_oer;
oer_type_encoder_f M_TMSI_encode_oer;
per_type_decoder_f M_TMSI_decode_uper;
per_type_encoder_f M_TMSI_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _M_TMSI_H_ */
#include <asn_internal.h>
