/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn1c/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -D /home/sid/mme/binds/src/s1ap/c -fcompound-names -no-gen-example`
 */

#ifndef	_MDTMode_H_
#define	_MDTMode_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ImmediateMDT.h"
#include "LoggedMDT.h"
#include "MDTMode-Extension.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MDTMode_PR {
	MDTMode_PR_NOTHING,	/* No components present */
	MDTMode_PR_immediateMDT,
	MDTMode_PR_loggedMDT,
	/* Extensions may appear below */
	MDTMode_PR_mDTMode_Extension
} MDTMode_PR;

/* MDTMode */
typedef struct MDTMode {
	MDTMode_PR present;
	union MDTMode_u {
		ImmediateMDT_t	 immediateMDT;
		LoggedMDT_t	 loggedMDT;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		MDTMode_Extension_t	 mDTMode_Extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MDTMode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MDTMode;
extern asn_CHOICE_specifics_t asn_SPC_MDTMode_specs_1;
extern asn_TYPE_member_t asn_MBR_MDTMode_1[3];
extern asn_per_constraints_t asn_PER_type_MDTMode_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _MDTMode_H_ */
#include <asn_internal.h>
