/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn1c/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -D /home/sid/mme/binds/src/s1ap/c -fcompound-names -no-gen-example`
 */

#ifndef	_MeasurementThresholdL1LoggedMDT_H_
#define	_MeasurementThresholdL1LoggedMDT_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Threshold-RSRP.h"
#include "Threshold-RSRQ.h"
#include "ProtocolIE-SingleContainer.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MeasurementThresholdL1LoggedMDT_PR {
	MeasurementThresholdL1LoggedMDT_PR_NOTHING,	/* No components present */
	MeasurementThresholdL1LoggedMDT_PR_threshold_RSRP,
	MeasurementThresholdL1LoggedMDT_PR_threshold_RSRQ,
	MeasurementThresholdL1LoggedMDT_PR_choice_Extensions
} MeasurementThresholdL1LoggedMDT_PR;

/* MeasurementThresholdL1LoggedMDT */
typedef struct MeasurementThresholdL1LoggedMDT {
	MeasurementThresholdL1LoggedMDT_PR present;
	union MeasurementThresholdL1LoggedMDT_u {
		Threshold_RSRP_t	 threshold_RSRP;
		Threshold_RSRQ_t	 threshold_RSRQ;
		ProtocolIE_SingleContainer_8146P0_t	 choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasurementThresholdL1LoggedMDT_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasurementThresholdL1LoggedMDT;
extern asn_CHOICE_specifics_t asn_SPC_MeasurementThresholdL1LoggedMDT_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasurementThresholdL1LoggedMDT_1[3];
extern asn_per_constraints_t asn_PER_type_MeasurementThresholdL1LoggedMDT_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _MeasurementThresholdL1LoggedMDT_H_ */
#include <asn_internal.h>
