/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn1c/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -D /home/sid/mme/binds/src/s1ap/c -fcompound-names -no-gen-example`
 */

#include "NB-IoT-PagingDRX.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_NB_IoT_PagingDRX_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_NB_IoT_PagingDRX_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  5 }	/* (0..5,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_NB_IoT_PagingDRX_value2enum_1[] = {
	{ 0,	3,	"v32" },
	{ 1,	3,	"v64" },
	{ 2,	4,	"v128" },
	{ 3,	4,	"v256" },
	{ 4,	4,	"v512" },
	{ 5,	5,	"v1024" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_NB_IoT_PagingDRX_enum2value_1[] = {
	5,	/* v1024(5) */
	2,	/* v128(2) */
	3,	/* v256(3) */
	0,	/* v32(0) */
	4,	/* v512(4) */
	1	/* v64(1) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_NB_IoT_PagingDRX_specs_1 = {
	asn_MAP_NB_IoT_PagingDRX_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_NB_IoT_PagingDRX_enum2value_1,	/* N => "tag"; sorted by N */
	6,	/* Number of elements in the maps */
	7,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NB_IoT_PagingDRX_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NB_IoT_PagingDRX = {
	"NB-IoT-PagingDRX",
	"NB-IoT-PagingDRX",
	&asn_OP_NativeEnumerated,
	asn_DEF_NB_IoT_PagingDRX_tags_1,
	sizeof(asn_DEF_NB_IoT_PagingDRX_tags_1)
		/sizeof(asn_DEF_NB_IoT_PagingDRX_tags_1[0]), /* 1 */
	asn_DEF_NB_IoT_PagingDRX_tags_1,	/* Same as above */
	sizeof(asn_DEF_NB_IoT_PagingDRX_tags_1)
		/sizeof(asn_DEF_NB_IoT_PagingDRX_tags_1[0]), /* 1 */
	{ &asn_OER_type_NB_IoT_PagingDRX_constr_1, &asn_PER_type_NB_IoT_PagingDRX_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NB_IoT_PagingDRX_specs_1	/* Additional specs */
};

