/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn1c/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -D /home/sid/mme/binds/src/s1ap/c -fcompound-names -no-gen-example`
 */

#ifndef	_PagingProbabilityInformation_H_
#define	_PagingProbabilityInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PagingProbabilityInformation {
	PagingProbabilityInformation_p00	= 0,
	PagingProbabilityInformation_p05	= 1,
	PagingProbabilityInformation_p10	= 2,
	PagingProbabilityInformation_p15	= 3,
	PagingProbabilityInformation_p20	= 4,
	PagingProbabilityInformation_p25	= 5,
	PagingProbabilityInformation_p30	= 6,
	PagingProbabilityInformation_p35	= 7,
	PagingProbabilityInformation_p40	= 8,
	PagingProbabilityInformation_p45	= 9,
	PagingProbabilityInformation_p50	= 10,
	PagingProbabilityInformation_p55	= 11,
	PagingProbabilityInformation_p60	= 12,
	PagingProbabilityInformation_p65	= 13,
	PagingProbabilityInformation_p70	= 14,
	PagingProbabilityInformation_p75	= 15,
	PagingProbabilityInformation_p80	= 16,
	PagingProbabilityInformation_p85	= 17,
	PagingProbabilityInformation_p90	= 18,
	PagingProbabilityInformation_p95	= 19,
	PagingProbabilityInformation_p100	= 20
	/*
	 * Enumeration is extensible
	 */
} e_PagingProbabilityInformation;

/* PagingProbabilityInformation */
typedef long	 PagingProbabilityInformation_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PagingProbabilityInformation_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PagingProbabilityInformation;
extern const asn_INTEGER_specifics_t asn_SPC_PagingProbabilityInformation_specs_1;
asn_struct_free_f PagingProbabilityInformation_free;
asn_struct_print_f PagingProbabilityInformation_print;
asn_constr_check_f PagingProbabilityInformation_constraint;
ber_type_decoder_f PagingProbabilityInformation_decode_ber;
der_type_encoder_f PagingProbabilityInformation_encode_der;
xer_type_decoder_f PagingProbabilityInformation_decode_xer;
xer_type_encoder_f PagingProbabilityInformation_encode_xer;
oer_type_decoder_f PagingProbabilityInformation_decode_oer;
oer_type_encoder_f PagingProbabilityInformation_encode_oer;
per_type_decoder_f PagingProbabilityInformation_decode_uper;
per_type_encoder_f PagingProbabilityInformation_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PagingProbabilityInformation_H_ */
#include <asn_internal.h>
