/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-PDU-Contents"
 * 	found in "asn1c/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -D /home/sid/mme/binds/src/s1ap/c -fcompound-names -no-gen-example`
 */

#ifndef	_ResetType_H_
#define	_ResetType_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ResetAll.h"
#include "UE-associatedLogicalS1-ConnectionListRes.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ResetType_PR {
	ResetType_PR_NOTHING,	/* No components present */
	ResetType_PR_s1_Interface,
	ResetType_PR_partOfS1_Interface
	/* Extensions may appear below */
	
} ResetType_PR;

/* ResetType */
typedef struct ResetType {
	ResetType_PR present;
	union ResetType_u {
		ResetAll_t	 s1_Interface;
		UE_associatedLogicalS1_ConnectionListRes_t	 partOfS1_Interface;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ResetType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResetType;

#ifdef __cplusplus
}
#endif

#endif	/* _ResetType_H_ */
#include <asn_internal.h>
