/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn1c/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -D /home/sid/mme/binds/src/s1ap/c -fcompound-names -no-gen-example`
 */

#ifndef	_SourceNodeID_H_
#define	_SourceNodeID_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SourceNgRanNode-ID.h"
#include "SourceNodeID-Extension.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SourceNodeID_PR {
	SourceNodeID_PR_NOTHING,	/* No components present */
	SourceNodeID_PR_sourceNgRanNode_ID,
	SourceNodeID_PR_sourceNodeID_Extension
} SourceNodeID_PR;

/* SourceNodeID */
typedef struct SourceNodeID {
	SourceNodeID_PR present;
	union SourceNodeID_u {
		SourceNgRanNode_ID_t	 sourceNgRanNode_ID;
		SourceNodeID_Extension_t	 sourceNodeID_Extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SourceNodeID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SourceNodeID;

#ifdef __cplusplus
}
#endif

#endif	/* _SourceNodeID_H_ */
#include <asn_internal.h>
