/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn1c/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -D /home/sid/mme/binds/src/s1ap/c -fcompound-names -no-gen-example`
 */

#ifndef	_TargetID_H_
#define	_TargetID_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TargeteNB-ID.h"
#include "TargetRNC-ID.h"
#include "CGI.h"
#include "TargetNgRanNode-ID.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TargetID_PR {
	TargetID_PR_NOTHING,	/* No components present */
	TargetID_PR_targeteNB_ID,
	TargetID_PR_targetRNC_ID,
	TargetID_PR_cGI,
	/* Extensions may appear below */
	TargetID_PR_targetgNgRanNode_ID
} TargetID_PR;

/* TargetID */
typedef struct TargetID {
	TargetID_PR present;
	union TargetID_u {
		TargeteNB_ID_t	 targeteNB_ID;
		TargetRNC_ID_t	 targetRNC_ID;
		CGI_t	 cGI;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		TargetNgRanNode_ID_t	 targetgNgRanNode_ID;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TargetID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TargetID;

#ifdef __cplusplus
}
#endif

#endif	/* _TargetID_H_ */
#include <asn_internal.h>
