/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn1c/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -D /home/sid/mme/binds/src/s1ap/c -fcompound-names -no-gen-example`
 */

#ifndef	_UL_CP_SecurityInformation_H_
#define	_UL_CP_SecurityInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UL-NAS-MAC.h"
#include "UL-NAS-Count.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* UL-CP-SecurityInformation */
typedef struct UL_CP_SecurityInformation {
	UL_NAS_MAC_t	 ul_NAS_MAC;
	UL_NAS_Count_t	 ul_NAS_Count;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UL_CP_SecurityInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UL_CP_SecurityInformation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolExtensionContainer.h"

#endif	/* _UL_CP_SecurityInformation_H_ */
#include <asn_internal.h>
