/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn1c/s1ap-r17.3.0/36413-h30.asn"
 * 	`asn1c -D /home/sid/mme/binds/src/s1ap/c -fcompound-names -no-gen-example`
 */

#ifndef	_WarningAreaList_H_
#define	_WarningAreaList_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ECGIList.h"
#include "TAIListforWarning.h"
#include "EmergencyAreaIDList.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum WarningAreaList_PR {
	WarningAreaList_PR_NOTHING,	/* No components present */
	WarningAreaList_PR_cellIDList,
	WarningAreaList_PR_trackingAreaListforWarning,
	WarningAreaList_PR_emergencyAreaIDList
	/* Extensions may appear below */
	
} WarningAreaList_PR;

/* WarningAreaList */
typedef struct WarningAreaList {
	WarningAreaList_PR present;
	union WarningAreaList_u {
		ECGIList_t	 cellIDList;
		TAIListforWarning_t	 trackingAreaListforWarning;
		EmergencyAreaIDList_t	 emergencyAreaIDList;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WarningAreaList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WarningAreaList;

#ifdef __cplusplus
}
#endif

#endif	/* _WarningAreaList_H_ */
#include <asn_internal.h>
