[package]
name = "binds"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bindgen = "0.71.1"
cc = {version = "1.2.7", features = ["parallel"]}
syn = {version = "2.0.95", features = ["full", "printing"]}
